config/routes.rb
Rails.application.routes.draw do

  get 'page/contact',as: "contact"

  get 'page/about',as: "about"

  get 'page/privacy'

  resources :controlsites
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Ckeditor::Engine => '/ckeditor'
  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :sitemap, only: :index
  get 'sitemap.xml', controller: "sitemap", action: "xml"

  get "posts/:id", to: redirect("/%{id}")
  resources :posts, path: '',except: [:new, :index, :create]
  resources :categories
  resources :users
  root 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :controlsites


  acts_as_taggable

  scope :published, -> { where.not(published_at: nil) }
  scope :unpublished, -> { where(published_at: nil) }

  has_attached_file :image, :styles => { :small => "100x100" },
                    :url  => "/assets/images/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/images/:id/:style/:basename.:extension"

  validates_presence_of :image, :title, :description, :user, :category, :format_post
  validates_attachment_presence :image
  validates_attachment_size :image, :less_than => 5.megabytes
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  extend FriendlyId

  friendly_id :title, use: [:slugged, :history, :finders]

  def should_generate_new_friendly_id?
    title_changed?
  end

  scope :of_post, lambda{
    where("format_post = 'Post'")
  }
  scope :of_slide, lambda{
    where("format_post = 'Slide'")
  }
  scope :of_trending, lambda{
    where("format_post = 'Trending'")
  }

  scope :in_category, lambda{ |cate_id|
    where("category_id = ?", cate_id)
  }

  def previous
    @post = Post.where(["id < ?", id]).order(:id).last
  end

  def next
    @post = Post.where(["id > ?", id]).order(:id).first
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @slides = Post.of_slide.limit(4).order("created_at desc")
      @recent = Post.of_post.limit(7).order("created_at desc")
      @posts = Post.of_post.order(:created_at).page(params[:page])
      @trending = Post.of_trending.order("created_at desc").last(1)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show

    if request.path != post_path(@post)
      return redirect_to @post, :status => :moved_permanently
    end
    @meta_title = @post.title
    @meta_description = @post.description

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :image, :description, :user_id, :category_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :image
    = f.file_field :image
  .field
    = f.label :descirption
    = f.text_area :descirption
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :category
    = f.text_field :category
  .actions
    = f.submit 'Save'

app/views/posts/_post.html.haml
%div.post.loop-panel.content-panel.add-active.content-panel-default.clearfix
  .loop-image-wrapper
    = link_to "", post, class: "loop-link"
    .loop-image-default.b-lazy.b-loaded.b-loaded{:style => "background-image: url('#{post.image}');"}
  .loop-info-wrapper
    .loop-info
      %h2.article-title.no-padding
        = link_to post do
          %span.title-text 
            = post.title
      .aa_item_info_block
        .excerpt 
          = truncate( raw( sanitize(post.description, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 140, :omission => "...")
    .bottom-loop-info
      %span
        by
        = link_to post.user.username, root_path
      %span.aa_item_time  
        - if post.created_at > Time.now.beginning_of_day
          = "#{time_ago_in_words(post.created_at)} ago"
        - else
          = post.created_at.strftime("%b %d, %Y")

app/views/posts/edit.html.haml
%h1 Editing post
= render 'form'

app/views/posts/index.html.haml
.after_header
  .row
    .col-md-12
      .container-inner
        .slide-top
          - @slides.each do |post|
            .post_slide
              = link_to post, class: 'overlay-link' do
                .slide_image_wrapper
                  .slide_image{:style => "background-image: url('#{post.image}')"}
                  .overlay
                .slide_footer
                  .aa_hfp_cat_block.aa_cat_name_block
                    = link_to post.category.name, root_path
                  %h3.aa_hfp_title
                    = link_to post.title, post
                  %span.aa-item-description.aa_hfp_author
                    by
                    = link_to post.user.username, '#'
                  %span.aa_item_time.aa-item-description
                    - if post.created_at > Time.now.beginning_of_day
                      = "#{time_ago_in_words(post.created_at)} ago"
                    - else
                      = post.created_at.strftime("%b %d, %Y")

.row.ads1
  .col-md-8.col-md-offset-2.text-center
    - @social.each do |p|
      = p.ads1.html_safe
.row
  .col-md-12
    .container-inner
      .row#control_wrapper
        .col-md-8.loop-column
          .post-container
            .bar-header.aa_home_bar_header.clearfix
              .bar-label-wrapper
                .bar-label
                  .label-text Latest News
            .content-inner.clearfix
              = render @posts
              = paginate @posts
        .col-md-4.mobile_display
          .content-panel.loop-sidebar-right
            .widget.clearfix
              .ads2
                - @social.each do |p|
                  = p.ads2.html_safe
              #aa_it_latest_articles-7.widget.clearfix
                .post-container.widget-panel.compact-header
                  .bar-header.clearfix
                    .bar-label
                      .label-text
                        %a{:href => "#"} Deal
                  - @recent.each do |post|
                    .compact-panel.widget_a.add-active.clearfix.deals_item
                      = link_to post do
                        .article-image-wrapper
                          .article-image{:style => "background-image: url('#{post.image}')"}
                        .article-info
                          .article-title
                            = post.title
                .post-container.widget-panel.compact-header
                  .bar-header.clearfix
                    .bar-label
                      .label-text
                        %a{:href => "#"} SUNDAY GIVEAWAY
                  .content-inner.clearfix
                    - @trending.each do |post|
                      .loop.widget-loop
                        .overlay-panel.add-active.clearfix
                          = link_to post do
                            .article-image-wrapper.b-lazy.b-loaded{:style => "background: url('#{post.image}');"}
              .ads.dpode
                - @social.each do |p|
                  = p.ads2.html_safe

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
.row
  .col-md-12
    .container-inner
      %h1.main-title.single-title.entry-title
        = @post.title
      .row#control_wrapper
        .col-md-8.single-post-selector
          .single-page
            .post-content.post-selector.active
              .aa_item_info_block.aa_top_info_block
                .postinfo.pull-right
                  .post-categories
                    .category-list
                      %span.aa_cat_name_block
                        = link_to @post.category.name
                %a.aa_postauthor_link{:href => "#"}
                  = image_tag @post.user.avatar,size: "32x32", class: "avatar avatar-32 photo"
                  %span
                    by
                    %span.aa_item_author 
                      = @post.user.username
                %span.aa_item_time 
                  - if @post.created_at > Time.now.beginning_of_day
                    = "#{time_ago_in_words(@post.created_at)} ago"
                  - else
                    = @post.created_at.strftime("%b %d, %Y")
              .aa_item_info_block.aa_top_info_block        
                .single_share_block.single_post_additional_block.short
                  .aa_socials.single_socs.clearfix
                    %a.soc.fb.window.activated{:href => "https://www.facebook.com/sharer.php?app_id=598473026880919&u=http://www.androidauthority.com/samsung-pay-early-access-registrations-now-open-india-754530/&t=Samsung+Pay+early+access+registrations+now+open+in+India", :rel => "me", :target => "_blank", :title => "Share on Facebook"}
                      %i.fa.fa-facebook-official
                    %a.soc.tw.window.activated{:href => "https://twitter.com/intent/tweet?url=http://www.androidauthority.com/samsung-pay-early-access-registrations-now-open-india-754530/&text=Samsung+Pay+early+access+registrations+now+open+in+India", :rel => "me", :target => "_blank", :title => "Share on Twitter"}
                      %i.fa.fa-twitter
                    %a.soc.g.window.activated{:href => "https://plus.google.com/share?url=http://www.androidauthority.com/samsung-pay-early-access-registrations-now-open-india-754530/", :rel => "me", :target => "_blank", :title => "Share on Google +"}
                      %i.fa.fa-youtube
              %p            
                =link_to image_tag(@post.image), @post.image(:original), :popup=>['original_image', 'height=700,width=900'],class: 'image-link'

              = @post.description.html_safe
              .aa_item_info_block.aa_bottom_info_block
                .postinfo
                  .post-categories
                    .category-list
                      %span.aa_cat_name_block
                        %a{:href => "http://www.androidauthority.com/news/", :title => "View all posts in News"} News
                  .aa-item-icon.aa-item-tags.post-tags
                    .tag-list
                      %i.fa.fa-tags
                      = raw @post.tag_list.map { |t| link_to t, tag_path(t),class: "nuans-neo-reloaded" }.join(', ') 
                - if @post.source.present?
                  .aa_source_link_wrapper.aa-item-icon.aa_item_source
                    = link_to @post.source, @post.url_source, class: "aa_source_link", :target => "_blank"
                - if @post.via.present?
                  .aa_via_link_wrapper.aa-item-icon.aa_item_via
                    = link_to @post.via, @post.url_via, class: "aa_via_link", :target => "_blank"


          #comments-753924.aa_comments_wrapper.clear
            .aa_comments_more.primary-button.aa-full-width-button.aa_comments_button{"data-id" => "753924"}
              %span
                Show
                %span.meta-comments.metric.info-right{"data-original-title" => "Comments", :title => ""}
                  -# %span.numcount
                comments

          .none          
            #disqus_thread
            :javascript
            
              var disqus_config = function () {
              this.page.url = "#{request.original_url}";  
              this.page.identifier = "#{@post.id}";
              };

              (function() { // DON'T EDIT BELOW THIS LINE
              var d = document, s = d.createElement('script');
              s.src = 'https://xnxx-5.disqus.com/embed.js';
              s.setAttribute('data-timestamp', +new Date());
              (d.head || d.body).appendChild(s);
              })();
            %noscript
              Please enable JavaScript to view the
              %a{:href => "https://disqus.com/?ref_noscript"} comments powered by Disqus.