config/routes.rb
Rails.application.routes.draw do

  get 'page/contact',as: "contact"

  get 'page/about',as: "about"

  get 'page/privacy'

  resources :controlsites
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Ckeditor::Engine => '/ckeditor'
  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :sitemap, only: :index
  get 'sitemap.xml', controller: "sitemap", action: "xml"

  get "posts/:id", to: redirect("/%{id}")
  resources :posts, path: '',except: [:new, :index, :create]
  resources :categories
  resources :users
  root 'posts#index'
end

app/models/controlsite.rb
class Controlsite < ApplicationRecord
  belongs_to :post
  has_attached_file :logo, :styles => { :small => "100x100" },
                  :url  => "/assets/images/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/images/:id/:style/:basename.:extension"

  validates_attachment_size :logo, :less_than => 5.megabytes
  validates_attachment_content_type :logo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/controlsites_controller.rb
class ControlsitesController < InheritedResources::Base

  private

    def controlsite_params
      params.require(:controlsite).permit(:logo, :facebook, :twitter, :youtube, :pinterest, :google, :plus, :ads1, :ads2, :ads3, :ads4, :post_id)
    end
end

app/helpers/controlsites_helper.rb
module ControlsitesHelper
end

app/views/controlsites/_form.html.haml
= form_for @controlsite do |f|
  - if @controlsite.errors.any?
    #error_explanation
      %h2= "#{pluralize(@controlsite.errors.count, "error")} prohibited this controlsite from being saved:"
      %ul
        - @controlsite.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :logo
    = f.text_field :logo
  .field
    = f.label :facebook
    = f.text_field :facebook
  .field
    = f.label :twitter
    = f.text_field :twitter
  .field
    = f.label :youtube
    = f.text_field :youtube
  .field
    = f.label :pinterest
    = f.text_field :pinterest
  .field
    = f.label :google
    = f.text_field :google
  .field
    = f.label :plus
    = f.text_field :plus
  .field
    = f.label :ads1
    = f.text_area :ads1
  .field
    = f.label :ads2
    = f.text_area :ads2
  .field
    = f.label :ads3
    = f.text_area :ads3
  .field
    = f.label :ads4
    = f.text_area :ads4
  .field
    = f.label :post
    = f.text_field :post
  .actions
    = f.submit 'Save'

app/views/controlsites/edit.html.haml
%h1 Editing controlsite

= render 'form'

= link_to 'Show', @controlsite
\|
= link_to 'Back', controlsites_path

app/views/controlsites/index.html.haml
%h1 Listing controlsites

%table
  %thead
    %tr
      %th Logo
      %th Facebook
      %th Twitter
      %th Youtube
      %th Pinterest
      %th Google
      %th Plus
      %th Ads1
      %th Ads2
      %th Ads3
      %th Ads4
      %th Post
      %th
      %th
      %th

  %tbody
    - @controlsites.each do |controlsite|
      %tr
        %td= controlsite.logo
        %td= controlsite.facebook
        %td= controlsite.twitter
        %td= controlsite.youtube
        %td= controlsite.pinterest
        %td= controlsite.google
        %td= controlsite.plus
        %td= controlsite.ads1
        %td= controlsite.ads2
        %td= controlsite.ads3
        %td= controlsite.ads4
        %td= controlsite.post
        %td= link_to 'Show', controlsite
        %td= link_to 'Edit', edit_controlsite_path(controlsite)
        %td= link_to 'Destroy', controlsite, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Controlsite', new_controlsite_path

app/views/controlsites/new.html.haml
%h1 New controlsite

= render 'form'

= link_to 'Back', controlsites_path

app/views/controlsites/show.html.haml
%p#notice= notice

%p
  %b Logo:
  = @controlsite.logo
%p
  %b Facebook:
  = @controlsite.facebook
%p
  %b Twitter:
  = @controlsite.twitter
%p
  %b Youtube:
  = @controlsite.youtube
%p
  %b Pinterest:
  = @controlsite.pinterest
%p
  %b Google:
  = @controlsite.google
%p
  %b Plus:
  = @controlsite.plus
%p
  %b Ads1:
  = @controlsite.ads1
%p
  %b Ads2:
  = @controlsite.ads2
%p
  %b Ads3:
  = @controlsite.ads3
%p
  %b Ads4:
  = @controlsite.ads4
%p
  %b Post:
  = @controlsite.post

= link_to 'Edit', edit_controlsite_path(@controlsite)
\|
= link_to 'Back', controlsites_path